# Generated by Django 5.2.9 on 2026-01-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Publicly accessible without login')),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.TextField(blank=True, help_text='Base64 encoded logo or URL')),
                ('layout_config', models.JSONField(default=dict, help_text='Grid layout configuration for panels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('health_problem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='health_problems.healthproblemtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('filter_type', models.CharField(choices=[('select', 'Single Select'), ('multiselect', 'Multi Select'), ('date', 'Date'), ('date_range', 'Date Range'), ('text', 'Text Search'), ('number_range', 'Number Range')], max_length=20)),
                ('field_path', models.CharField(help_text='Path to the field in data (e.g., patient.state, severity)', max_length=255)),
                ('options', models.JSONField(blank=True, default=list, help_text='Static options or query for dynamic options')),
                ('default_value', models.JSONField(blank=True, help_text='Default filter value', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='dashboards.dashboard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chart_type', models.CharField(choices=[('bar_vertical', 'Vertical Bar Chart'), ('bar_horizontal', 'Horizontal Bar Chart'), ('bar_grouped', 'Grouped Bar Chart'), ('bar_stacked', 'Stacked Bar Chart'), ('line', 'Line Chart'), ('area', 'Area Chart'), ('pie', 'Pie Chart'), ('donut', 'Donut Chart'), ('scatter', 'Scatter Plot'), ('choropleth', 'Choropleth Map (Brazil)'), ('table', 'Data Table'), ('metric', 'Single Metric/KPI'), ('flowchart', 'Flow Diagram'), ('timeline', 'Timeline'), ('heatmap', 'Heatmap')], max_length=30)),
                ('data_source', models.JSONField(default=dict, help_text='Configuration for data query (model, fields, filters)')),
                ('x_axis_field', models.CharField(blank=True, help_text='Field for X axis', max_length=255)),
                ('y_axis_field', models.CharField(blank=True, help_text='Field for Y axis', max_length=255)),
                ('aggregation', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average'), ('min', 'Minimum'), ('max', 'Maximum'), ('distinct', 'Distinct Count')], default='count', max_length=20)),
                ('group_by', models.CharField(blank=True, help_text='Field to group data by', max_length=255)),
                ('chart_config', models.JSONField(default=dict, help_text='Chart-specific configuration (colors, legend, tooltips, etc.)')),
                ('show_legend', models.BooleanField(default=True)),
                ('show_values', models.BooleanField(default=True)),
                ('show_grid', models.BooleanField(default=True)),
                ('x_axis_label', models.CharField(blank=True, max_length=255)),
                ('y_axis_label', models.CharField(blank=True, max_length=255)),
                ('color_scheme', models.JSONField(blank=True, default=list, help_text='Custom color palette for chart')),
                ('grid_position', models.JSONField(default=dict, help_text='Position in dashboard grid (x, y, width, height)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='dashboards.dashboard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DashboardTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('header', 'Header'), ('description', 'Description'), ('note', 'Note'), ('source', 'Data Source'), ('methodology', 'Methodology')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('style_config', models.JSONField(default=dict, help_text='Styling configuration (font size, color, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='dashboards.dashboard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit'), ('admin', 'Full Admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dashboards.dashboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dashboard', 'user')},
            },
        ),
    ]
