# Generated by Django 5.2.9 on 2025-12-21 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('has_options', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('object_repr', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='clipboard-list', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('question_schema', models.JSONField(default=dict, help_text='JSON schema defining the form questions for this health problem type')),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_problem_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('select', 'Single Select'), ('multiselect', 'Multi Select'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('autocomplete', 'Autocomplete'), ('file', 'File Upload')], max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select/multiselect/radio fields')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules (min, max, pattern, etc.)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(blank=True, help_text='Group questions by section', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_problem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_questions', to='health_problems.healthproblemtype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PatientHealthProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('monitoring', 'Under Monitoring'), ('resolved', 'Resolved'), ('chronic', 'Chronic')], default='active', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('schema_version_used', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_health_problems', to=settings.AUTH_USER_MODEL)),
                ('health_problem_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_instances', to='health_problems.healthproblemtype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_problems', to='patients.patient')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_health_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient Health Problems',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text='JSON object with question_id: answer pairs')),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_form_responses', to=settings.AUTH_USER_MODEL)),
                ('patient_health_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='health_problems.patienthealthproblem')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
