# Generated by Django 5.2.9 on 2026-01-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_dashboards',
            field=models.BooleanField(default=False, help_text='Can create new dashboards'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_patients',
            field=models.BooleanField(default=False, help_text='Can create/edit/delete patients'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_reports',
            field=models.BooleanField(default=False, help_text='Can create/edit/delete reports'),
        ),
    ]
